name: Ping Backend Every 10 Minutes

on:
  schedule:
    - cron: "*/10 * * * *"  # her 10 dakikada bir
  workflow_dispatch:  # istersen manuel tetikleyebil

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to backend
        run: |
          curl -X GET https://one01-otomatik-tas-dizme.onrender.com || true
